// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSFsvCs2r3DJJ9SS5Gwp2j91ipubiwKFA',
    appId: '1:1089784102705:web:ba5e6d41fe86563c377a10',
    messagingSenderId: '1089784102705',
    projectId: 'purvis-vogue',
    authDomain: 'purvis-vogue.firebaseapp.com',
    storageBucket: 'purvis-vogue.firebasestorage.app',
    measurementId: 'G-889YVQPLS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe8hLgWvPTHYAJRR3I7vgtKHY-ZrWr4aI',
    appId: '1:1089784102705:android:5e21560994aec055377a10',
    messagingSenderId: '1089784102705',
    projectId: 'purvis-vogue',
    storageBucket: 'purvis-vogue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzZim9n8KznhVMXCEw2mnSJc11LVmXS-0',
    appId: '1:1089784102705:ios:5249256772f6682b377a10',
    messagingSenderId: '1089784102705',
    projectId: 'purvis-vogue',
    storageBucket: 'purvis-vogue.firebasestorage.app',
    iosBundleId: 'com.example.purvisVogue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzZim9n8KznhVMXCEw2mnSJc11LVmXS-0',
    appId: '1:1089784102705:ios:5249256772f6682b377a10',
    messagingSenderId: '1089784102705',
    projectId: 'purvis-vogue',
    storageBucket: 'purvis-vogue.firebasestorage.app',
    iosBundleId: 'com.example.purvisVogue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSFsvCs2r3DJJ9SS5Gwp2j91ipubiwKFA',
    appId: '1:1089784102705:web:54b6eefe34d4fc50377a10',
    messagingSenderId: '1089784102705',
    projectId: 'purvis-vogue',
    authDomain: 'purvis-vogue.firebaseapp.com',
    storageBucket: 'purvis-vogue.firebasestorage.app',
    measurementId: 'G-9X7Y8TWEVS',
  );
}
